name: deploy-payments

on: 
  push:
    branches: 
      - master
    paths: 
      - 'client/**'
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: cd auth && docker -t mihndim2020/payments .
    - run docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push mihndim2020/payments   
    - uses: digitalocean/action-doctl@v2
      with: 
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save ticket-market 
    - run: kubectl rollout restart deployment payments-depl
